theme = "kanagawa"

[editor]
line-number = "relative"
scroll-lines = 1
auto-save=true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
p = "paste_clipboard_before"
y = "yank_main_selection_to_clipboard"
g = { a = "code_action" } # ga to open code actions
X = "extend_line_above" # Shift+x to select the whole line above

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

### https://docs.helix-editor.com/master/configuration.html#editorwhitespace-section
[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"    # Non Breaking SPace
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

[editor.statusline]
left = [ "mode", "spinner", "diagnostics" ]
center = [ "file-name", "separator", "version-control", "separator" ]
right = [ "position", "position-percentage", "total-line-numbers" ]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


