# Python configuration using pyright and ruff for linting
[[language]]
name = "python"
formatter = { command = "ruff" }

# JavaScript/TypeScript using tsserver


[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "efm-lsp-prettier" ]
# HTML, CSS, and JSON
[[language]]
name = "html"
language-servers = [ "vscode-html-languageserver" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-languageserver", ]

[[language]]
name = "json"
language-servers = [ "vscode-json-languageserver" ]
